"""Database module for DynamoDB table management."""

from src.db.table_schemas import (
    ALL_TABLE_SCHEMAS,
    ENTERPRISE_PROFILES_SCHEMA,
    VOICE_SESSIONS_SCHEMA,
    ACTION_PLANS_SCHEMA,
    FINANCIAL_DATA_SCHEMA,
    OPERATIONAL_DATA_SCHEMA,
    SCHEMES_SCHEMA,
    MANDI_PRICES_SCHEMA,
    ALERTS_SCHEMA,
    ANALYTICS_EVENTS_SCHEMA
)

__all__ = [
    "ALL_TABLE_SCHEMAS",
    "ENTERPRISE_PROFILES_SCHEMA",
    "VOICE_SESSIONS_SCHEMA",
    "ACTION_PLANS_SCHEMA",
    "FINANCIAL_DATA_SCHEMA",
    "OPERATIONAL_DATA_SCHEMA",
    "SCHEMES_SCHEMA",
    "MANDI_PRICES_SCHEMA",
    "ALERTS_SCHEMA",
    "ANALYTICS_EVENTS_SCHEMA"
]
